id = "dream-lang"
name = "Dream Lang"
version = "0.1.0"
schema_version = 1
authors = ["weaming"]
description = "Dream language support for Zed"
repository = "https://github.com/weaming/tree-sitter-dream/zed"

[grammars.dream]
repository = "https://github.com/weaming/tree-sitter-dream"
rev = "HEAD"

[language_servers.dream-language-server]
name = "Dream Language Server"
languages = ["Dream"]
